DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS dishes CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS foods_orders CASCADE;

CREATE TABLE clients (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  phone_number VARCHAR(255) NOT NULL
);

CREATE TABLE dishes (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  price INTEGER,
  img_url VARCHAR
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES clients(id) ON DELETE CASCADE,
  start_time TIMESTAMP,
  duration INTEGER  NOT NULL DEFAULT 20,
  note TEXT
);



CREATE TABLE foods_orders (
  id SERIAL PRIMARY KEY NOT NULL,
  dishes_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  quantity INTEGER  NOT NULL DEFAULT 1
);
